baseURL: "https://naga.network/"
languageCode: "en-us"
title: "NAGA ELECTRIC INDUSTRIAL CO., LTD."
theme: "PaperMod"

params:
  defaultTheme: "dark"
  disableThemeToggle: true
  ShowPostNavLinks: false
  ShowFooterCredits: false   # ğŸ‘ˆ removes â€œPowered by â€¦â€
  copyright: "Â© 4723 NAGA ELECTRIC INDUSTRIAL CO., LTD."


markup:
  goldmark:
    renderer:
      unsafe: true
